# Generated by Django 3.2.9 on 2021-11-23 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20211122_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(default=datetime.date(2021, 11, 23)),
        ),
    ]
