# Generated by Django 3.2.9 on 2021-12-02 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211125_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inn',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(default=datetime.date(2021, 12, 2)),
        ),
    ]
