# Generated by Django 3.2.9 on 2021-11-22 15:07

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 11, 22)),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=128, region=None),
        ),
    ]
