# Generated by Django 3.2.9 on 2021-11-22 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20211122_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 15, 9, 22, 464564, tzinfo=utc)),
        ),
    ]
