# Generated by Django 3.2.9 on 2021-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20211122_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='kari06@example.org', max_length=254),
        ),
    ]
