# Generated by Django 3.2.9 on 2021-11-25 16:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='brownelizabeth@example.org', max_length=254, validators=[core.validators.validate_email_for_prohibited_domain]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[core.validators.validate_phone]),
        ),
    ]
