# Generated by Django 3.2.9 on 2021-12-02 13:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_auto_20211125_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='smithmichelle@example.com', max_length=254, validators=[core.validators.validate_email_for_prohibited_domain]),
        ),
    ]
