# Generated by Django 3.2.9 on 2021-12-06 13:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='adrianschneider@example.org', max_length=254, validators=[core.validators.validate_email_for_prohibited_domain]),
        ),
    ]
