# Generated by Django 3.2.9 on 2021-12-06 15:01

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_number_of_students'),
        ('teachers', '0015_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='kimberly01@example.com', max_length=254, validators=[core.validators.validate_email_for_prohibited_domain]),
        ),
    ]
