# Generated by Django 3.2.9 on 2021-12-06 17:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_auto_20211206_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='jesseharris@example.net', max_length=254, validators=[core.validators.validate_email_for_prohibited_domain]),
        ),
    ]
