# Generated by Django 3.2.9 on 2021-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('num_year', models.IntegerField(default=1)),
                ('number_of_students', models.IntegerField()),
            ],
        ),
    ]
