# Generated by Django 3.2.9 on 2021-11-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number_of_students',
        ),
    ]
